### ISSUE TITLE
Howdy

### ISSUE THREAD

**Issue by thejohnfreeman** [tylerjl/aoc-hs#1]
I found your repo from Reddit. I was hoping to compare against other Haskell solutions. My solutions are [here](https://github.com/thejohnfreeman/advent-2015). Did you complete day 19? I'm stuck on part 2, trying to get my solution to run in a reasonable time. How do you run your solutions? I think the instructions in your README might be out of date; it does not work for me:

```
$ stack exec src/Y2015/D01.hs
src/Y2015/D01.hs: line 1: module: command not found
src/Y2015/D01.hs: line 2: level: command not found
src/Y2015/D01.hs: line 3: ,: command not found
src/Y2015/D01.hs: line 4: where: command not found
src/Y2015/D01.hs: line 6: syntax error near unexpected token `('
src/Y2015/D01.hs: line 6: `import Data.List (foldl')'
```

**Comment by tylerjl** [comment]
Hi! This is a woefully out-of-date response, but I didn't expect anyone to look this closely at my solutions and missed the issue. Sorry for that.

I've updated the README with up-to-date instructions; tl;dr I was mid-progress changing the way I wanted to run the code when I dropped working on the solutions.

As for day 19, I took the easy route and mimicked some other solutions that concluded that some molecules expanded while others didn't so it runs in O(n) without anything really fancy or smart.

Your solutions are great by the way, I'm learning from them as well. 👍
